const zombieGame = { canvas:null, ctx:null, running:true, player:{x:430,y:280,r:18,speed:3.2,health:100,ammo:12,reload:0}, bullets:[], zombies:[], pickups:[], keys:{}, score:0, wave:1, spawnTimer:0, flash:0 };
function initZombie(){ zombieGame.canvas=document.getElementById('zombieCanvas'); if(!zombieGame.canvas) return; zombieGame.ctx=zombieGame.canvas.getContext('2d'); restartZombie(); zombieGame.canvas.addEventListener('mousemove',(e)=>{ const rect=zombieGame.canvas.getBoundingClientRect(); zombieGame.mouseX=(e.clientX-rect.left)*(zombieGame.canvas.width/rect.width); zombieGame.mouseY=(e.clientY-rect.top)*(zombieGame.canvas.height/rect.height); }); zombieGame.canvas.addEventListener('click', shootBullet); window.addEventListener('keydown',(e)=>{ const k=e.key.toLowerCase(); zombieGame.keys[k]=true; if(k==='r') reloadZombie(); }); window.addEventListener('keyup',(e)=> zombieGame.keys[e.key.toLowerCase()]=false); requestAnimationFrame(zombieLoop); }
function restartZombie(){ zombieGame.player={x:430,y:280,r:18,speed:3.2,health:100,ammo:12,reload:0}; zombieGame.bullets=[]; zombieGame.zombies=[]; zombieGame.pickups=[]; zombieGame.score=0; zombieGame.wave=1; zombieGame.spawnTimer=0; zombieGame.running=true; zombieGame.flash=0; for(let i=0;i<5;i++) spawnZombie(); renderZombieHud(); }
function spawnZombie(){ const side=Math.floor(Math.random()*4); let x=0,y=0; const w=zombieGame.canvas.width, h=zombieGame.canvas.height; if(side===0){x=Math.random()*w;y=-20;} else if(side===1){x=w+20;y=Math.random()*h;} else if(side===2){x=Math.random()*w;y=h+20;} else {x=-20;y=Math.random()*h;} zombieGame.zombies.push({x,y,r:16 + Math.random()*8,speed:0.7 + Math.random()*0.6 + zombieGame.wave*0.06,hp:2 + Math.floor(Math.random()*2)}); }
function shootBullet(){ if(!zombieGame.running || zombieGame.player.reload>0) return; if(zombieGame.player.ammo<=0){beep(180,0.05,'square',0.015);return;} const dx=zombieGame.mouseX-zombieGame.player.x, dy=zombieGame.mouseY-zombieGame.player.y; const len=Math.hypot(dx,dy)||1; zombieGame.bullets.push({x:zombieGame.player.x,y:zombieGame.player.y,dx:dx/len*7.5,dy:dy/len*7.5,r:4,life:80}); zombieGame.player.ammo -= 1; zombieGame.flash = 3; }
function reloadZombie(){ if(zombieGame.player.reload>0 || zombieGame.player.ammo===12) return; zombieGame.player.reload = 40; }
function updateZombie(){ if(!zombieGame.running) return; const p=zombieGame.player; let mx=0,my=0; if(zombieGame.keys['z']||zombieGame.keys['w']||zombieGame.keys['arrowup']) my -= 1; if(zombieGame.keys['s']||zombieGame.keys['arrowdown']) my += 1; if(zombieGame.keys['q']||zombieGame.keys['a']||zombieGame.keys['arrowleft']) mx -= 1; if(zombieGame.keys['d']||zombieGame.keys['arrowright']) mx += 1; const ml=Math.hypot(mx,my)||1; p.x += (mx/ml)*p.speed*(mx||my?1:0); p.y += (my/ml)*p.speed*(mx||my?1:0); p.x=Math.max(p.r,Math.min(zombieGame.canvas.width-p.r,p.x)); p.y=Math.max(p.r,Math.min(zombieGame.canvas.height-p.r,p.y)); if(p.reload>0){ p.reload--; if(p.reload===0) p.ammo=12; } if(zombieGame.flash>0) zombieGame.flash--; zombieGame.spawnTimer++; if(zombieGame.spawnTimer>Math.max(45,120-zombieGame.wave*4)){ zombieGame.spawnTimer=0; spawnZombie(); } zombieGame.bullets.forEach(b=>{ b.x+=b.dx; b.y+=b.dy; b.life--; }); zombieGame.bullets=zombieGame.bullets.filter(b=>b.life>0); zombieGame.zombies.forEach(z=>{ const dx=p.x-z.x, dy=p.y-z.y; const len=Math.hypot(dx,dy)||1; z.x += (dx/len)*z.speed; z.y += (dy/len)*z.speed; if(len < z.r + p.r) p.health -= 0.12; }); for(let i=zombieGame.zombies.length-1;i>=0;i--){ const z=zombieGame.zombies[i]; for(let j=zombieGame.bullets.length-1;j>=0;j--){ const b=zombieGame.bullets[j]; if(Math.hypot(z.x-b.x,z.y-b.y) < z.r+b.r){ z.hp--; zombieGame.bullets.splice(j,1); if(z.hp<=0){ zombieGame.score += 10; zombieGame.zombies.splice(i,1); } break; } } } if(p.health<=0){ p.health=0; zombieGame.running=false; if(zombieGame.score > (appState.scores.zombieBest||0)){ appState.scores.zombieBest=zombieGame.score; appState.scores.total += zombieGame.score; saveScores(); } } else if(zombieGame.score > (appState.scores.zombieBest||0)){ appState.scores.zombieBest=zombieGame.score; saveScores(); } renderZombieHud(); }
function drawZombie(){ if(!zombieGame.canvas) return; const ctx=zombieGame.ctx, c=zombieGame.canvas; ctx.clearRect(0,0,c.width,c.height); for(let x=0;x<c.width;x+=48) for(let y=0;y<c.height;y+=48){ ctx.fillStyle=((x+y)/48)%2===0?'rgba(255,255,255,.03)':'rgba(255,255,255,.02)'; ctx.fillRect(x,y,46,46); } zombieGame.bullets.forEach(b=>{ ctx.fillStyle='#ffed99'; ctx.beginPath(); ctx.arc(b.x,b.y,b.r,0,Math.PI*2); ctx.fill(); }); zombieGame.zombies.forEach(z=>{ ctx.fillStyle='#8aff9a'; ctx.beginPath(); ctx.arc(z.x,z.y,z.r,0,Math.PI*2); ctx.fill(); }); const p=zombieGame.player; ctx.fillStyle='#5de4ff'; ctx.beginPath(); ctx.arc(p.x,p.y,p.r,0,Math.PI*2); ctx.fill(); if(!zombieGame.running){ ctx.fillStyle='rgba(0,0,0,.45)'; ctx.fillRect(0,0,c.width,c.height); ctx.fillStyle='#fff'; ctx.textAlign='center'; ctx.font='bold 38px Arial'; ctx.fillText('Game Over', c.width/2, c.height/2 - 10); } }
function zombieLoop(){ updateZombie(); drawZombie(); requestAnimationFrame(zombieLoop); }
function renderZombieHud(){ const a=document.getElementById('zombieScore'); const b=document.getElementById('zombieHealth'); const c=document.getElementById('zombieAmmo'); const d=document.getElementById('zombieWave'); const e=document.getElementById('zombieBest'); if(a) a.textContent=zombieGame.score; if(b) b.textContent=Math.round(zombieGame.player.health); if(c) c.textContent=zombieGame.player.reload>0 ? 'rechargement...' : zombieGame.player.ammo; if(d) d.textContent=zombieGame.wave; if(e) e.textContent=appState.scores.zombieBest || 0; }
document.addEventListener('DOMContentLoaded', initZombie);
